resorts:
  # New Hampshire
  - id: cannon_mountain
    name: Cannon Mountain
    state: NH
    scraper: cannon_mountain
    latitude: 44.156
    longitude: -71.695
  - id: waterville_valley
    name: Waterville Valley Resort
    state: NH
    scraper: waterville_valley
    latitude: 43.95
    longitude: -71.512
  - id: ragged_mountain
    name: Ragged Mountain
    state: NH
    scraper: ragged_mountain
    latitude: 43.484
    longitude: -71.851
  - id: pats_peak
    name: Pat's Peak Mountain
    state: NH
    scraper: pats_peak
    latitude: 43.147
    longitude: -71.808
  - id: loon_mountain
    name: Loon Mountain
    state: NH
    scraper: loon_mountain
    latitude: 44.037
    longitude: -71.621
  # Vermont
  - id: okemo
    name: Okemo Mountain Resort
    state: VT
    scraper: okemo
    latitude: 43.401
    longitude: -72.717
  - id: jay_peak
    name: Jay Peak Resort
    state: VT
    scraper: jay_peak
    latitude: 44.937
    longitude: -72.504
  - id: bolton_valley
    name: Bolton Valley
    state: VT
    scraper: bolton_valley
    latitude: 44.422
    longitude: -72.846
  - id: killington
    name: Killington
    state: VT
    scraper: killington
    latitude: 43.605
    longitude: -72.82
  - id: pico
    name: Pico Mountain
    state: VT
    scraper: pico
    latitude: 43.664
    longitude: -72.844
  - id: sugarbush
    name: Sugarbush Resort
    state: VT
    scraper: sugarbush
    latitude: 44.145
    longitude: -72.894
  - id: stratton
    name: Stratton Mountain Resort
    state: VT
    scraper: stratton
    latitude: 43.114
    longitude: -72.908
  # Maine
  - id: saddleback
    name: Saddleback Mountain
    state: ME
    scraper: saddleback
    latitude: 44.948
    longitude: -70.514
  - id: sugarloaf
    name: Sugarloaf
    state: ME
    scraper: sugarloaf
    latitude: 45.031
    longitude: -70.313
  - id: sunday_river
    name: Sunday River
    state: ME
    scraper: sunday_river
    latitude: 44.473
    longitude: -70.856
scrapers:
  cannon_mountain:
    report_url: https://www.cannonmt.com/mountain-report
    selectors: {}
  okemo:
    report_url: https://www.onthesnow.com/vermont/okemo-mountain-resort/skireport
    selectors: {}
  waterville_valley:
    report_url: https://www.onthesnow.com/new-hampshire/waterville-valley/skireport
    selectors: {}
  ragged_mountain:
    report_url: https://www.raggedmountainresort.com/mountain-report-cams/
    selectors: {}
  pats_peak:
    report_url: https://www.onthesnow.com/new-hampshire/pats-peak/skireport
    selectors: {}
  loon_mountain:
    report_url: https://www.onthesnow.com/new-hampshire/loon-mountain/skireport
    selectors: {}
  jay_peak:
    report_url: https://www.onthesnow.com/vermont/jay-peak/skireport
    selectors: {}
  bolton_valley:
    report_url: https://www.onthesnow.com/vermont/bolton-valley/skireport
    selectors: {}
  killington:
    report_url: https://www.onthesnow.com/vermont/killington-resort/skireport
    selectors: {}
  pico:
    report_url: https://www.onthesnow.com/vermont/pico-mountain-at-killington/skireport
    selectors: {}
  sugarbush:
    report_url: https://www.onthesnow.com/vermont/sugarbush/skireport
    selectors: {}
  stratton:
    report_url: https://www.onthesnow.com/vermont/stratton-mountain/skireport
    selectors: {}
  saddleback:
    report_url: https://www.onthesnow.com/maine/saddleback-inc/skireport
    selectors: {}
  sugarloaf:
    report_url: https://www.onthesnow.com/maine/sugarloaf/skireport
    selectors: {}
  sunday_river:
    report_url: https://www.onthesnow.com/maine/sunday-river/skireport
    selectors: {}
scheduler:
  cron: "0 6,18 * * *"
  enabled: true
logging:
  level: INFO
  json: true
scoring:
  base_score: 50.0
  max_score: 100.0
  min_score: 0.0
  base_depth_floor: 18.0
  base_depth_weight: 0.5
  gust_penalty_threshold: 25.0
  gust_penalty_per_mph: 0.75
  fresh_snow_bonus_per_inch: 2.0
  powder_bonus: 12.0
  icy_penalty: 15.0
  closed_resort_penalty: 35.0
  unknown_status_penalty: 10.0
  missing_metric_penalty: 5.0
  low_base_penalty_per_inch: 0.75
